Milestone 9: add devise
ITurres/blog_app pull request #9
Opened 2023-12-13 21:41 UTC by ITurres

## Pull Request Summary for Milestone 9 Completion

- [x] All [requirements](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/blog_app_devise.md#project-requirements) completed.

---

2023-12-13 22:26 UTC, Shedrack-Sunday requested changes
Hello @ITurres     👋 

# CHANGES REQUIRED ♻️

Impressive work on the project so far👏
You've done extremely well so far in this project,  However, there are some adjustments you need to make to move to the next project. 💯

![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights   
- Good use of GitHub features ✔️   
- Nice work with  Devise features ✔️
- Great work on the  Authorization implementation 👏   



# - Required Changes  🌵  

- [ ] Kindly note  the comment i made regarding the issues on enabling the `:onfirmable` feature to make sure signup is confirmed 
# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing really improves your application.



Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-12-13 22:26 UTC, Shedrack-Sunday commented on app/models/user.rb
> +  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
- [ ] Kindly enable `:confirmable` to make it possible to get a confirmation after login 👍

2023-12-13 22:26 UTC, Shedrack-Sunday commented on db/migrate/20231213164642_add_devise_to_users.rb
> +      # t.string   :unconfirmed_email # Only if using reconfirmable
- [ ] Do well to uncomment this section, to make sure the confirmable configuration works 👍

2023-12-13 23:42 UTC, ITurres commented
Holly Molly, we have overlooked that @demesameneshoa ! 🥲

Hi @Shedrack-Sunday! thank you so much for having reviewed this PR! You are right!, We'll fix it right away 🎯
We'll also make sure to modify the views to math the current design.

Thank you again! 🥂

2023-12-14 00:19 UTC, V-Blaze approved these changes
Hi @ITurres, @demesameneshoa  

# Approved 🟢 🟢 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![giphy](https://user-images.githubusercontent.com/107632780/229644741-7dea3027-bf3f-4416-855b-46095e3bf6d5.gif)

## Highlights

- Devise setup correctly 💯
-  Great communication with reviewer👍
-  Correct git flow🟢 👍

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-12-14 00:26 UTC, ITurres commented
Wow great! 🥳. Thank you @V-Blaze! We both wish you a great week! thank you for reviewing the PR.

2023-12-14 00:26 UTC, merged